config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users

  resources :books


  root to: "homes#top"
  get "home/about" => "homes#about", as: "about"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
  validates :title, :body, presence: true
  validates :body, length: {maximum: 200}
  
  has_one_attached :image
  
  # 画像ない時のエラー回避メソッド
  def get_image
    if profile_image.attached?
      profile_image
    else
      'default-image.jpg'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books, dependent: :destroy
  
  validates :name, uniqueness: true
  validates :name, length: {in: 2..20}
  validates :introduction, length: {maximum: 50}
  
  has_one_attached :profile_image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  def get_image
    if profile_image.attached?
      profile_image
    else
      'default-image.jpg'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top, :about]
  
  def after_sign_in_path_for(resource)
    user_path(resource)
  end
  def after_sign_up_path_for(resource)
    user_path(resource)
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    # devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def index
    @book = Book.new
    @user = current_user
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user_id == current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @book.save
    redirect_to book_path(@book.id)
  end

  def index
    @user = current_user
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def destroy
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_partial.html.erb
    <div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag user.get_image, size: "100x100" %>
      <table class="table mb-3">
        <tr>
          <th>name</th>
          <th><%= user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= user.introduction %></th>
        </tr>
      </table>

        <%= link_to edit_user_path(user.id),class:"row pt-4 pb-3" do %>
          <button type="button" class="btn btn-outline-secondary btn-block"><i class="fas fa-user-cog"></i></button>
        <% end %>

      <h2>New book</h2>

      <%= form_with model: Book.new do |f| %>

        <div class="form-group mb-0">
        <label for="inputTitle" class="form-label">Title</label><br>
        <%= f.text_field :title, autofocus: true, id: "inputTitle", class: "btn-block form-control" %><br>
        </div>
        <div class="mt-0">
        <label for="inputOpinion" class="form-label">Opinion</label><br>
        <%= f.text_area :body, id: "inputOpinion", class: "btn-block form-control" %>
        </div>
        <%= f.submit "Create Book", class: "btn btn-success mt-3" %>

      <% end %>
    </div>

app/views/books/edit.html.erb
<div class="container">
  
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <h1>Editing Book</h1>
      <div class="errors">
        <% if @book.errors.any? %>
          <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
            <ul>
              <% @book.errors.full_messages.each do |message| %>
                <li>
                  <%= message %>
                </li>
              <% end %>
            </ul>
        <% end %>
      </div>
      <%= form_with model: @book do |f| %>

        <label for="inputTitle">Title</label><br>
        <%= f.text_field :title, autofocus: true, id:"inputTitle", class:"btn-block form-control" %><br>

        <label for="inputBody">Opinion</label><br>
        <%= f.text_area :body, id:"inputBody", class:"btn-block form-control" %><br>

        <%= f.submit "Update Book", class: "btn btn-success mb-3" %>

      <% end %>

    
    <%= link_to "Show", book_path(@book.id) %>
    |
    <%= link_to "Back", books_path %>
    <!--<a href="">back</a>-->
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
    <div class="errors">
      <% if @book.errors.any? %>
        <h2><%= @book.errors.count %> errors prohibited this obj from being saved:</h2>
          <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li>
              <%= message %>
            </li>
          <% end %>
          </ul>
      <% end %>
    </div>
  <div class="row">
    
    <%= render "partial", user: @user %>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover">
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th></th>
        </tr>

        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user_id) do %>
                <%= image_tag book.user.get_image, size: "80x80" %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <%= render "partial", user: @user %>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tr>
          <td>
            <%= link_to user_path(@book.user_id) do %>
              <%= image_tag @user.get_image, size: "100x100" %><br>
              <%= @user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book.id) %></td>
          <td><%= @book.body %></td>
          <% if @book.user_id == current_user.id %>
            <td>
              <%= link_to edit_book_path(@book.id) do %>
                <button type="button" class="btn btn-sm btn-success">Edit</button>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(@book.id), method: :delete, data: {confirm: "本当に消しますか？"} do %>
                <button type="button" class="btn btn-sm btn-danger">Destroy</button>
              <% end %>
            </td>
          <% end %>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="mx-auto mt-3">
      Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mt-3 mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
      <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions
      <p>about various books!</p>
      <div class="row">
        <div class="mx-auto col-10">
          <a class="btn btn-info btn-block btn-sm mb-3" href="/users/sign_in" role="button">Log in</a>
          <a class="btn btn-success btn-block btn-sm" href="/users/sign_up" role="button">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <header class="pb-0">

      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="#">Bookers</a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">

              <% if user_signed_in? %>
                <li class="nav-item active">
                  <%= link_to user_path(current_user.id), class: 'nav-link text-light' do%>
                    <i class="fas fa-home"></i><span class="ml-1">Home</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to users_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-users"></i><span class="ml-1">Users</span>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to books_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-book-open"></i><span class="ml-1">Books</span>
                  <% end %>
                </li>

                <li class="nav-item">
                  <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                    <i class="fas fa-sign-out-alt text-light"></i><span class="ml-1">Log out</span>
                  <% end %>
                </li>
              <% else %>
                <li class="nav-item active">
                  <a href="/" class="nav-link text-light"><i class="fas fa-home"></i><span class="ml-1">Home</span></a>
                </li>
                <li>
                  <%= link_to about_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-link"></i><span class="ml-1">About</span>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-user-plus"></i><span class="ml-1">Sign up</span>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to user_session_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-sign-in-alt"></i><span class="ml-1">Log in</span>
                  <% end %>
                </li>
              <% end %>
            </ul>
        </div>
      </nav>
    </header>
    <%= notice %>
    <%= alert %>
    <%= yield %>
    <footer class="mt-5">
      <div class="container text-center">
        <p>CopyRight Infratop.inc</p>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <div class="errors">
        <% if @user.errors.any? %>
          <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li>
                  <%= message %>
                </li>
              <% end %>
            </ul>
        <% end %>
      </div>
      <%= form_with model: @user do |f| %>

        <label for="inputName">Name</label><br>
        <%= f.text_field :name, autofocus: true, id:"inputName", class:"btn-block form-control" %><br>

        <label for="inputProfileImage">Image</label><br>
        <%= f.file_field :profile_image, accept: "image/*", class:"mb-3" %><br>

        <label for="inputIntroduction">Introduction</label><br>
        <%= f.text_area :introduction, id:"inputIntroduction", class:"btn-block form-control" %><br>

        <%= f.submit "Update User", class: "btn  mb-3 btn-secondary" %>

      <% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <%= render "books/partial", user: @user %>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <tr>
          <th>image</th>
          <th>name</th>
          <th class="colspan-3"></th>
        </tr>
        <% @users.each do |user| %>
          <tr>
            <td><%= image_tag user.get_image, size: "80x80" %></td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <%= render "books/partial", user: @user %>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table">
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
                <%= image_tag @user.get_image, size: "80x80" %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>